resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

#resources:
#- name: pull-requests
#  type: pull-request
#  source:
#    repository: itsdalmo/test-repository
#    access_token: ((github-access-token))

- name: pr
  type: git
  source:
    uri: https://github.com/ladean/shiloh.git
    branch: master

- name: ci
  type: git
  source:
    uri: https://github.com/concourse/ci

jobs:
- name: update-pr-pipelines
  plan:
  - get: ci
  - get: pr
    trigger: true
  - load_var: pr
    file: pull-requests/prs.json
  - across:
    - var: pr
      values: ((.:pull_requests))
    set_pipeline: prs
    file: pipes/child.yml
    instance_vars: {number: ((.:pr.number))}