resource_types:
- name: git-branches
  type: registry-image
  source:
    repository: aoldershaw/git-branches-resource

resources:
- name: branches
  type: git-branches
  source:
    uri: https://github.com/ladean/shiloh.git
    # The "(?P<name>pattern)" syntax defines a named capture group.
    # aoldershaw/git-branches-resource emits the value of each named capture
    # group under the `groups` key.
    #
    # e.g. feature/some-feature ==> {"groups": {"feature": "some-feature"}}
    branch_regex: 'feature/(?P<feature>.*)'

- name: pr
  type: git
  source:
    uri: https://github.com/ladean/shiloh.git

jobs:
- name: set-feature-pipelines
  plan:
  - in_parallel:
    - get: branches
      trigger: true
    - get: pr
  - load_var: branches
    file: feature-branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
    set_pipeline: dev
    file: pipes/pr_template.yml
    instance_vars: {feature: ((.:branch.groups.feature))}
    vars: {branch: ((.:branch.name))}
